# Alembic environment wired to the application settings and model metadata.
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import create_engine, pool

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.infrastructure.config.settings import get_settings  # noqa: E402
from src.infrastructure.database import models  # noqa: E402, F401
from src.infrastructure.database.base import Base  # noqa: E402

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

POSTGIS_TABLES = {"spatial_ref_sys", "geography_columns", "geometry_columns", "raster_columns"}


# Keeps PostGIS system tables out of autogenerated migrations.
def include_object(obj, name, type_, reflected, compare_to):  # noqa: ANN001, ANN201, ARG001
    return not (type_ == "table" and name in POSTGIS_TABLES)


# Emits SQL without connecting, used for generating migration scripts.
def run_migrations_offline() -> None:
    context.configure(
        url=get_settings().database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        include_object=include_object,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


# Applies migrations against a live database connection.
def run_migrations_online() -> None:
    engine = create_engine(get_settings().database_url, poolclass=pool.NullPool)
    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
